library(xts)
library(magrittr)
library(dplyr)
library(plotly)
library(ggplot2)
library(xts)
library(tidyr)
library(lubridate)

#' @description Build a cohort matrix from an activity feed.
#' @param activity_feed An xts object with two columns: user_id and activity.
#' @param transform_percent A logical indicating whether to transform the
#' matrix to percentages.
cohort_matrix <- function(activity_feed, transform_percent = TRUE) {
  if (!inherits(activity_feed, "data.frame") &&
        !inherits(activity_feed, "xts") &&
        !inherits(activity_feed, "tbl_df")) {
    stop("param activity_feed must be data.frame, xts, or tbl_df")
  }
  if (ncol(activity_feed) != 2 ||
        !("user_id" %in% colnames(activity_feed)) ||
        !("activity" %in% colnames(activity_feed))) {
    stop("activity_feed must have two columns user_id and activity")
  }
  # Transform feed.
  feed_df <- data.frame(index(activity_feed), coredata(activity_feed))
  names(feed_df) <- c("timestamp", "user_id", "activity")

  # Step 1: Convert timestamp to Date format and extract year_month
  feed_df$timestamp <- as.POSIXct(feed_df$timestamp, format="%Y-%m-%d %H:%M:%S")
  feed_df$year_month <- format(feed_df$timestamp, "%Y-%m")

  # Step 2: Group by user and get the first activity month
  user_cohort <- feed_df %>%
    group_by(user_id) %>%
    summarize(first_activity_month = min(year_month))

  # Step 3: Calculate the number of months since the first activity
  feed_df <- feed_df %>%
    left_join(user_cohort, by = "user_id") %>%
    mutate(months_since_first = interval(
      ymd(paste0(first_activity_month, "-01")), timestamp) %/% months(1))

  # Step 4: Build the cohorts matrix
  cohorts_matrix <- feed_df %>%
    group_by(first_activity_month, months_since_first) %>%
    summarize(active_users = n_distinct(user_id)) %>%
    pivot_wider(names_from = months_since_first,
                values_from = active_users,
                values_fill = 0)

  # Calculate cohorts in percentage
  cohorts_perc <- cohorts_matrix %>% mutate(across(`0`:`23`, ~ . / `0` * 100))
  matrix <- if (transform_percent) { cohorts_perc } else { cohorts_matrix }

  return(matrix)
}

#' @description Plot the cohort from a calculated cohorts matrix.
#' @param cohorts_matrix A data frame generated by cohort_matrix(feed)
plot_cohort <- function(cohorts_matrix) {
  # Pivot longer for plotting
  cohorts_long <- cohorts_matrix %>%
    pivot_longer(cols = -first_activity_month,
                 names_to = "month",
                 values_to = "percentage")

  # Convert month to numeric
  cohorts_long <- cohorts_long %>%
    mutate(month = as.numeric(month))

  # Create the ggplot heat map
  p <- ggplot(cohorts_long,
              aes(x = month,
                  y = first_activity_month,
                  fill = percentage,
                  text = sprintf("%.1f%%", percentage))) +
    geom_tile() +
    scale_fill_gradient(low = "white", high = "blue") +
    scale_y_discrete(
      limits = rev(levels(factor(cohorts_long$first_activity_month)))) +
      labs(
        title = "Cohort Retention Rate (%)",
        x = "Months since first activity",
        y = "First activity month"
      ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  # Convert ggplot to plotly for interactive tooltips
  p_plotly <- ggplotly(p, tooltip = "text")

  # Display the interactive plot
  p_plotly
}
